  - repo: local
    hooks:
      - id: frontend-lint
        name: Frontend Lint
        entry: cmd /c "cd logify && pnpm lint"
        language: system
        pass_filenames: false

      - id: frontend-format
        name: Frontend Format
        entry: cmd /c "cd logify && pnpm format"
        language: system
        pass_filenames: false